### ISSUE TITLE
Please fix the readme stating that Mantis supports macCatalyst but not macOS.

### ISSUE THREAD

**Issue by ShikiSuen** [guoyingtao/Mantis#429]
Strictly saying, supporting macOS and supporting macCatalyst are two different things. The former strictly relies on AppKit with zero dependency to UIKit. The latter is vice-versa.

<img width="278" alt="image" src="https://github.com/user-attachments/assets/3312d674-a3af-49b8-8c10-3e7c34574306" />

<img width="851" alt="image" src="https://github.com/user-attachments/assets/cc54f3fd-1c9d-49d8-95d3-bf98c7fe233c" />

**Comment by guoyingtao** [comment]
@ShikiSuen 

The README initially stated that Mantis only supports Catalyst.

_Mantis is an iOS image cropping library written in Swift, designed to mimic the Photo app and provide rich cropping interactions for your iOS or Mac app (**Catalyst-only**)._


Mac Catalyst requires macOS 10.15 or later as the minimum deployment target, which is why macOS 10.15 is listed as a requirement.

**Comment by ShikiSuen** [comment]
@guoyingtao Then the macOS target needs to be removed from `package.swift`.
