### ISSUE TITLE
Rotate only image and not the cropper and vice-versa

### ISSUE THREAD

**Issue by zeeshanTeks** [guoyingtao/Mantis#85]
Hi @guoyingtao 

Is it possible to rotate only the image with a button click? And rotate only the cropper(i.e., the ratio is reversed) with a button click?

**Comment by guoyingtao** [comment]
@zeeshanTeks The current version of Mantis does not support it.
Do you want Mantis support this feature instead of #83 
Or do you want both?

**Comment by zeeshanTeks** [comment]
@guoyingtao  Both would be really helpful. Thanks.

**Comment by guoyingtao** [comment]
@zeeshanTeks I added rotate cropper button in the branch `85_rotate_image_cropper_separately`
It is actually altering the cropper ratio not rotating. I am not sure if it is what you want.
You can test it in the branch `85_rotate_image_cropper_separately`

<img width="298" alt="image" src="https://user-images.githubusercontent.com/26723384/108614741-3d5d1d80-73cb-11eb-9a41-cc3776fec13b.png">
<img width="340" alt="image" src="https://user-images.githubusercontent.com/26723384/108614747-52d24780-73cb-11eb-9dad-ee49b2558460.png">

**Comment by zeeshanTeks** [comment]
@guoyingtao Thank you so much, this works perfectly.

**Comment by guoyingtao** [comment]
@zeeshanTeks I released Mantis 1.4.11 which includes this feature.
You can add the button to alter the cropper by adding `.alterCropper90Degree` to `config.cropToolbarConfig.toolbarButtonOptions`

```Swift
        var config = Mantis.Config()
        config.cropToolbarConfig.toolbarButtonOptions = [.clockwiseRotate, .reset, .ratio, .alterCropper90Degree];
```

**Comment by zeeshanTeks** [comment]
Thanks a lot. You are too good.

**Comment by marko8994** [comment]
@guoyingtao, as I see in the version this only gives option to independently rotate image and cropper.  Is it possible to make an option to have fixed ratio even after image is rotated.

Example:

1. We have custom ratio 3:4
2. We rotate image 90 degrees clockwise
3. Custom ratio stays 3:4 even after rotation, instead of changing to 4:3 like it doing now

I believe that this can be partly related to issue #87 so if you decide that this can be implemented bear it in mind.
If you need any help, I would be happy to contribute. Thanks in advance.
